name: QCaliper
slug: qcaliper
description: Calibrador y logger de pulsos de riego para Home Assistant.
version: 1.0.0
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
init: false
homeassistant_api: true
ingress: true
ingress_port: 8080
panel_icon: mdi:water-plus
panel_title: QCaliper
map:
  - data:rw
  - config:ro
options: {}
schema: {}
